---
title: "GA_SA_Profallio"
author: "Srihari"
date: "5 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(GenSA)
library(GA)
library(ggplot2)
```

#### Portfolio Optimization - GenSA
```{r}
library("quantmod")
tickers <- c("JNJ", "SONC", "SRE", "BAC", "DIS")
getSymbols(tickers, from = "2000-12-01", to = "2018-11-01")
P <- NULL
for(ticker in tickers) {
 tmp <- Cl(to.monthly(eval(parse(text = ticker))))
 P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES
obj <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out <- tmp1 + 1e3 * tmp2
 return(out)
}
```
```{r}
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj, lower = rep(0, 5), upper = rep(1, 5), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
wstar.GenSA <- out.GenSA$par
wstar.GenSA <- wstar.GenSA / sum(wstar.GenSA)
rbind(tickers, round(100 * wstar.GenSA, 2))
100 * (sum(wstar.GenSA * mu) - mean(mu))
wstar.GenSA
```

#### Portfolio Optimization - Genetic Algorithem


```{r}
library("quantmod")
tickers <- c("JNJ", "SONC", "SRE", "BAC", "DIS")
getSymbols(tickers, from = "2000-12-01", to = "2018-11-02")
P <- NULL
for(ticker in tickers) {
 tmp <- Cl(to.monthly(eval(parse(text = ticker))))
 P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES

obj <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out <- tmp1 + 1e3 * tmp2 
 return(out)
 
}


```
### Applying Rastrigin function
```{r}
Rastrigin <- function(x1, x2)
{
  20 + x1^2 + x2^2 - 10*(cos(2*pi*x1) + cos(2*pi*x2))
}

x1 <- x2 <- seq(-5.12, 5.12, by = 0.1)
```


```{r}
set.seed(2234)
fn.call <<- 0
gap <- ga(type = "real-valued",fitness=function(w)-Rastrigin(w[1],w[2]),lower=rep(0,5),upper=rep(1,5), popSize = 1,maxiter = 30)


fn.call.gap <- fn.call


summary(gap)
plot(gap)

```
#### GA vs GenSA
```{r}
solution_Gensa <-c('0.30152351', '0.14410247', '0.29768502', '0.06092723', '0.19576178')
solution_ga <-c('0.1535262', '0.4118706', '0.184994', '0.1944339', '0.5000719')
data.frame(solution_ga,solution_Gensa)

print('Number of Itterations=3000')

fitness_value_ga<-c('-23.0017  ')
fitness_value_Gensa<- c('10.08017638') 
data.frame(fitness_value_ga,fitness_value_Gensa)

```
